name: PermaWorldGenerator
description: Permanent world generator.
author: DjDCH
main: com.djdch.bukkit.permaworldgenerator.PermaWorldGenerator
version: 0.1
load: startup
website: http://dev.bukkit.org/server-mods/permaworldgenerator/
